[ci] Trigger action release via workflow input

diff --git a/.github/workflows/release-action.yml b/.github/workflows/release-action.yml
--- a/.github/workflows/release-action.yml
+++ b/.github/workflows/release-action.yml
@@ -1,25 +1,44 @@
 name: Release Action
 
 on:
-  release:
-    types: [released]
+  workflow_dispatch:
+    inputs:
+      version:
+        description: 'Version to release'
+        required: true
 
 jobs:
+  validate-version:
+    runs-on: ubuntu-latest
+    name : Validate Version
+    steps:
+      - name: Validate version input
+        run: |
+          if [[ ! "${{ github.event.inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Version '${{ github.event.inputs.version }}' is not a valid semver format."
+            exit 1
+          fi
+          echo "Version '${{ github.event.inputs.version }}' is valid."
+
   build-artifacts:
+    needs: validate-version
     strategy:
       fail-fast: false
       matrix:
         include:
           - target: x86_64-unknown-linux-musl
             os: ubuntu-latest
+            name: Linux
           - target: x86_64-apple-darwin
             os: macos-latest
+            name: macOS
           - target: x86_64-pc-windows-msvc
             os: windows-latest
+            name: Windows
             file_extension: .exe
 
     runs-on: ${{ matrix.os }}
-    name: ${{ matrix.target }}
+    name: Build ${{ matrix.name }}
     env:
       binary_name: action${{ matrix.file_extension }}
 
@@ -66,4 +85,4 @@ jobs:
         uses: ncipollo/release-action@v1
         with:
           artifacts: "Linux/Linux.tgz,macOS/macOS.tgz,Windows/Windows.tgz"
-          tag: ${{ github.event.release.tag_name }}
+          tag: v${{ github.event.inputs.version }}
